# Generated by Django 6.0.7 on 2026-07-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('job', 'Job Opportunity'), ('internship', 'Internship Opportunity'), ('startup', 'Startup Opportunity'), ('scholarship', 'Scholarship Opportunity'), ('learning', 'Learning Opportunity'), ('networking', 'Networking Opportunity')], max_length=20)),
                ('priority_score', models.IntegerField(default=50)),
                ('impact_score', models.IntegerField(default=50)),
                ('urgency_score', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('applied', 'Applied'), ('completed', 'Completed'), ('ignored', 'Ignored')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
