# Generated by Django 6.0.7 on 2026-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
